base_config:
  app_name: "otp_service"
  app_tokens:
    - QA_TOKEN
    - DEV_TOKEN
    - UAT_TOKEN

  server_config:
    address: "0.0.0.0"
    port: 2010
    keep_alive_time: 10
    keep_alive_time_out: 10

  gateway_config:
    enabled: true
    address: "0.0.0.0"
    port: 2011
    url: "/otp_svc"
    swagger_file: ""
    endpoint: "/otp_svc/"

  database_config:
    type: "mysql"
    host_name: "0.0.0.0"
    port: 3306
    user_name: root
    database_name: otp_service

  trace_provider_url: "http://0.0.0.0:14268/api/traces"
  log_level: DEBUG

otp_length: 6